parallel all the applications

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -45,7 +45,7 @@ steps:
     dir: 'applications/rag/'
     waitFor: ['validate platform']
 
-  # Create cluster to test ray, jupyterhub
+  # Create cluster to test ray, jupyterhub, rag
   - id: 'create gke cluster'
     name: 'gcr.io/$PROJECT_ID/terraform'
     env:
@@ -65,7 +65,9 @@ steps:
         -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
         -var=autopilot_cluster=$_AUTOPILOT_CLUSTER \
         -var=cluster_location=$_REGION \
-        -auto-approve -no-color -lock=false
+        -var=cpu_pools=[{.initial_node_count=2}] \
+        -var=gpu_pools=[{.initial_node_count=2}] \
+        -auto-approve -no-color 
         echo "pass" > /workspace/gke_cluster_result.txt
     dir: 'infrastructure/'
     allowFailure: true
@@ -95,7 +97,7 @@ steps:
         -var=workload_identity_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
         -var=gcs_bucket=gke-aieco-ray-$SHORT_SHA-$_BUILD_ID \
         -var=enable_gpu=true \
-        -auto-approve -no-color -lock=false
+        -auto-approve -no-color 
         echo "pass" > /workspace/user_result.txt
 
         # Make sure pods are running
@@ -118,18 +120,23 @@ steps:
       - |
         set -e
 
-        cd /workspace/applications/ray/
-        terraform destroy \
-        -var-file=workloads.tfvars \
-        -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=cluster_location=$_REGION \
-        -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID-ray \
-        -var=workload_identity_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=gcs_bucket=gke-aieco-ray-$SHORT_SHA-$_BUILD_ID \
-        -var=enable_gpu=true \
-        -auto-approve -no-color -lock=false
+        if [[ $(cat /workspace/user_result.txt) = "pass" ]] && [[ $(cat /workspace/ray_result.txt) = "pass" ]]; then
+          echo "ray API succeeded, deleting ray cluster"
 
+          cd /workspace/applications/ray/
+          terraform destroy \
+          -var-file=workloads.tfvars \
+          -var=project_id=$PROJECT_ID \
+          -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+          -var=cluster_location=$_REGION \
+          -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID-ray \
+          -var=workload_identity_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
+          -var=gcs_bucket=gke-aieco-ray-$SHORT_SHA-$_BUILD_ID \
+          -var=enable_gpu=true \
+          -auto-approve -no-color
+        else
+          echo " ray test failed, leaking ray cluster resources"
+        fi
     allowFailure: true
     waitFor: ['test ray cluster']
 
@@ -153,19 +160,17 @@ steps:
         -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID-jupyter \
         -var=workload_identity_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
         -var=gcs_bucket=gke-aieco-jupyter-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color -lock=false
+        -auto-approve -no-color 
         echo "pass" > /workspace/jupyterhub_tf_result.txt
 
-        kubectl get pods -n ml-$SHORT_SHA-$_BUILD_ID-jupyter 
-        kubectl wait --all pods -n ml-$SHORT_SHA-$_BUILD_ID-jupyter --for=condition=Ready --timeout=1500s
-        kubectl get pods -n ml-$SHORT_SHA-$_BUILD_ID-jupyter 
+        kubectl wait --for=condition=Ready pods -n ml-$SHORT_SHA-$_BUILD_ID-jupyter -l 'component!=continuous-image-puller' --timeout=1800s
         kubectl get services -n ml-$SHORT_SHA-$_BUILD_ID-jupyter
-        kubectl port-forward -n ml-$SHORT_SHA-$_BUILD_ID-jupyter service/proxy-public 9443:80 &
+        kubectl port-forward -n ml-$SHORT_SHA-$_BUILD_ID-jupyter service/proxy-public 9442:80 &
         # Wait port-forwarding to take its place
         sleep 5s
 
         cd /workspace/modules/jupyter/tests
-        python3 test_hub.py "127.0.0.1:9443" $_AUTOPILOT_CLUSTER
+        python3 test_hub.py "127.0.0.1:9442" $_AUTOPILOT_CLUSTER
         echo "pass" > /workspace/jupyterhub_test_result.txt
     allowFailure: true
     waitFor: ['create gke cluster']
@@ -178,19 +183,22 @@ steps:
       - |
         set -e
 
-        cd /workspace/applications/jupyter/
-        terraform destroy \
-        -var-file=workloads-without-iap.example.tfvars \
-        -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=cluster_location=$_REGION \
-        -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID-jupyter \
-        -var=workload_identity_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=gcs_bucket=gke-aieco-jupyter-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color -lock=false
+        if [[ $(cat /workspace/jupyterhub_tf_result.txt) = "pass" ]] && [[ $(cat /workspace/jupyterhub_test_result.txt) = "pass" ]]; then
+          echo "jupyter test succeeded, deleting jupyterhub resources"
 
-        kubectl get events
-
+          cd /workspace/applications/jupyter/
+          terraform destroy \
+          -var-file=workloads-without-iap.example.tfvars \
+          -var=project_id=$PROJECT_ID \
+          -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+          -var=cluster_location=$_REGION \
+          -var=kubernetes_namespace=ml-$SHORT_SHA-$_BUILD_ID-jupyter \
+          -var=workload_identity_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
+          -var=gcs_bucket=gke-aieco-jupyter-$SHORT_SHA-$_BUILD_ID \
+          -auto-approve -no-color
+        else
+          echo "Jupyterhub test failed, leaking jupyterhub resources"
+        fi
     allowFailure: true
     waitFor: ['test jupyterhub']
 
@@ -225,15 +233,14 @@ steps:
         -var=kubernetes_namespace=rag-$SHORT_SHA-$_BUILD_ID \
         -var=gcs_bucket=gke-aieco-rag-$SHORT_SHA-$_BUILD_ID \
         -var=ray_service_account=ray-sa-4-rag-$SHORT_SHA-$_BUILD_ID \
+        -var=rag_service_account=rag-sa-4-rag-$SHORT_SHA-$_BUILD_ID \
         -var=jupyter_service_account=jupyter-sa-4-rag-$SHORT_SHA-$_BUILD_ID \
-        -var=rag_service_account=rag-sa-$SHORT_SHA-$_BUILD_ID \
         -var=cloudsql_instance=pgvector-instance-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color -lock=false
+        -auto-approve -no-color 
         echo "pass" > /workspace/rag_tf_result.txt
 
         # Validate Ray: Make sure pods are running
-        kubectl get pods -n rag-$SHORT_SHA-$_BUILD_ID
-        kubectl wait --all pods -n rag-$SHORT_SHA-$_BUILD_ID --for=condition=Ready --timeout=1200s
+        kubectl wait --for=condition=Ready pods -n rag-$SHORT_SHA-$_BUILD_ID -l 'component!=continuous-image-puller' --timeout=1200s
         kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/ray-cluster-kuberay-head-svc 8262:8265 &
         # Wait port-forwarding to take its place
         sleep 5s
@@ -245,13 +252,13 @@ steps:
 
         # Validate JupyterHub: Get hub url
         kubectl get services -n rag-$SHORT_SHA-$_BUILD_ID
-        kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/proxy-public 9442:80 &
+        kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/proxy-public 9443:80 &
         # Wait port-forwarding to take its place
         sleep 5s
 
         # Validate JupyterHub: Test Hub
         cd /workspace/modules/jupyter/tests
-        python3 test_hub.py "127.0.0.1:9442" $_AUTOPILOT_CLUSTER
+        python3 test_hub.py "127.0.0.1:9443" $_AUTOPILOT_CLUSTER
         echo "pass" > /workspace/rag_jupyterhub_test_result.txt
 
         # Validate RAG: Test rag frontend
@@ -270,7 +277,7 @@ steps:
         kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID $(kubectl get pod -l app=jupyterhub,component=hub -n rag-$SHORT_SHA-$_BUILD_ID -o jsonpath="{.items[0].metadata.name}") -- jupyterhub token admin --log-level=CRITICAL | xargs python3 ./applications/rag/notebook_starter.py
         # Wait for jupyterhub to trigger notebook pod startup
         sleep 5s
-        kubectl wait --for=condition=Ready pod/jupyter-admin -n rag-$SHORT_SHA-$_BUILD_ID --timeout=300s
+        kubectl wait --for=condition=Ready pod/jupyter-admin -n rag-$SHORT_SHA-$_BUILD_ID --timeout=500s
         kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- jupyter nbconvert --to script /data/rag-kaggle-ray-sql-interactive.ipynb
         kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- ipython /data/rag-kaggle-ray-sql-interactive.py
 
@@ -287,46 +294,33 @@ steps:
       - '-c'
       - |
         set -e
+        
+        if [[ $(cat /workspace/rag_tf_result.txt) = "pass" ]] && [[ $(cat /workspace/rag_ray_dashboard_result.txt) != "pass" ]] && [[ $(cat /workspace/rag_jupyterhub_test_result.txt) != "pass" ]]; then
+          echo "rag tests succeeded"
 
-        cd /workspace/applications/rag/
-        terraform destroy \
-        -var-file=workloads.tfvars \
-        -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
-        -var=create_cluster=false \
-        -var=jupyter_add_auth=false \
-        -var=frontend_add_auth=false \
-        -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=cluster_location=$_REGION \
-        -var=kubernetes_namespace=rag-$SHORT_SHA-$_BUILD_ID \
-        -var=gcs_bucket=gke-aieco-rag-$SHORT_SHA-$_BUILD_ID \
-        -var=ray_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=rag_service_account=rag-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=jupyter_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
-        -var=cloudsql_instance=pgvector-instance-$SHORT_SHA-$_BUILD_ID \
-        -auto-approve -no-color
+          cd /workspace/applications/rag/
+          terraform destroy \
+          -var-file=workloads.tfvars \
+          -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
+          -var=create_cluster=false \
+          -var=jupyter_add_auth=false \
+          -var=frontend_add_auth=false \
+          -var=project_id=$PROJECT_ID \
+          -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+          -var=cluster_location=$_REGION \
+          -var=kubernetes_namespace=rag-$SHORT_SHA-$_BUILD_ID \
+          -var=gcs_bucket=gke-aieco-rag-$SHORT_SHA-$_BUILD_ID \
+          -var=ray_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
+          -var=rag_service_account=rag-sa-$SHORT_SHA-$_BUILD_ID \
+          -var=jupyter_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
+          -var=cloudsql_instance=pgvector-instance-$SHORT_SHA-$_BUILD_ID \
+          -auto-approve -no-color
+        else
+          echo "rag test failed, leaking rag resources"
+        fi
 
     allowFailure: true
     waitFor: ['test rag']
-
-  - id: 'cleanup gke cluster'
-    name: 'gcr.io/$PROJECT_ID/terraform'
-    entrypoint: 'bash'
-    args:
-      - '-c'
-      - |
-        set -e
-
-        cd /workspace/infrastructure
-        terraform destroy -var-file=tfvars_tests/standard-gke-public.platform.tfvars -var=project_id=$PROJECT_ID \
-        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-        -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
-        -var=subnetwork_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
-        -var=autopilot_cluster=$_AUTOPILOT_CLUSTER \
-        -var=cluster_location=$_REGION -auto-approve -no-color
-
-    allowFailure: true
-    waitFor: ['cleanup rag']
 
   - id: 'check result'
     name: 'gcr.io/$PROJECT_ID/terraform'
@@ -383,8 +377,27 @@ steps:
           echo "rag prompt test failed"
           exit 1
         fi
+    # waitFor: ['cleanup gke cluster']
+    waitFor: ['cleanup rag', 'cleanup jupyterhub', 'cleanup ray cluster']
 
-    waitFor: ['cleanup gke cluster']
+  - id: 'cleanup gke cluster'
+    name: 'gcr.io/$PROJECT_ID/terraform'
+    entrypoint: 'bash'
+    args:
+      - '-c'
+      - |
+        set -e
+
+        cd /workspace/infrastructure
+        terraform destroy -var-file=tfvars_tests/standard-gke-public.platform.tfvars -var=project_id=$PROJECT_ID \
+        -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+        -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
+        -var=subnetwork_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
+        -var=autopilot_cluster=$_AUTOPILOT_CLUSTER \
+        -var=cluster_location=$_REGION -auto-approve -no-color
+
+    allowFailure: true
+    waitFor: ['check result']
         
 substitutions:
   _REGION: us-east4
